server:
  port: 8000
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
          username: root
          password: Shocker8250698
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://localhost:3306/mybatis_plus2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
          username: root
          password: Shocker8250698
          driver-class-name: com.mysql.cj.jdbc.Driver

#MyBatis Plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true # 驼峰转换
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler #枚举处理器
    type-enums-package: com.ai94.base.api.constant.**,com.ai94.whatsapp.api.constant.** #枚举包
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志打印


#租户表
app:
  isolated:
    tables:
      - t_user
      - t_display_name
      - t_number
      - t_chart
      - t_hangup_message